### PR TITLE
Return the catalog path as catalog id

### PR DESCRIPTION
**Pull request by qgau**
The implementation and the doc seems to consider the catalog ID as its full path from root.
Hence it makes more sense to return the full path as ID when getting a catalog.
Be aware that I tested it against my instance but I may have missed some side effects.

### CODE REVIEW

**Comment by jjrom** [comment]
What is stored in the catalog table and what is returned in the API are two different things. The fact that the id is a full path in the catalog table is to guarantee the absolute unicity of homonym catalogs that have different paths. 
However, from the API point of view, the id of the catalog should be seen as the "directory" name in a files hierarchy. From this perspective, I'm not sure that is logical to have the full path as the id. This has to be discussed.

**Comment by qgau** [comment]
I never mentionned table or DB, from a REST perspective, either the path is the id, or the endpoint should be different.

**Comment by jjrom** [comment]
Sorry I misunderstood your first comment - you mentioned the "implementation" and the table structure is part of the implementation thus my comment on its content vs what is displayed.

I'm still not convince from that the id should be the path. For instance a collection is a catalog - also the same naming should be applied i.e. collection id should be the path i.e. "collections/collectionId" and not "collectionId" ? From an homogeneous approach, the same should also be applied for the item identifier that should then be "collections/collectionId/featureId" instead of "featureId".

By pushing this logic, one could argue that the id should then be the fully qualified url and not the local path thus "http://example.com/catalogs/catalog1/catalog2/etc.".

**Comment by qgau** [comment]
OK I got your point.
Up to me, there are no issue with Collections and Items/Features as it respects REST resource management.
For catalog it can be discussed indeed.
But in fact, the more I think about it, I don't think that is an issue, my idea was to retrieve the path easily, and I can do that with the `self` link. So I don't really need that change, if you are hesitating, just reject the PR, no problem :-)

**Pull request closed without merging**
